# Generated by Django 4.2 on 2023-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_service", "0002_remove_tickets_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickets",
            name="seatNumber",
        ),
        migrations.AddField(
            model_name="tickets",
            name="seat_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tickets",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
