# Generated by Django 4.2 on 2023-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_service', '0002_remove_tickets_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='showtime',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='seatNumber',
        ),
        migrations.AddField(
            model_name='tickets',
            name='seat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tickets',
            name='showtime_id',
            field=models.IntegerField(default=0),
        ),
    ]
